/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { AddRecordRequestDto } from './addRecordRequestDto';

export type AddRecordBody = {
  requestDto: AddRecordRequestDto;
  /** 기록증 사진 */
  recordImage: Blob;
};
