/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { AddRecordRequestDtoCourse } from './addRecordRequestDtoCourse';

export interface AddRecordRequestDto {
  /** 대회 ID (raceId 또는 raceTitle 중 하나만 입력) */
  raceId?: number;
  /** 대회명 (raceId 또는 raceTitle 중 하나만 입력) */
  raceTitle?: string;
  /** 배번 */
  bib?: string;
  /** 대회 날짜 */
  raceDate?: string;
  /** 참여코스 */
  course?: AddRecordRequestDtoCourse;
  /** 기록 (HH:mm:ss 형식) */
  record?: string;
}
