/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { AuthStatusDtoMessage } from './authStatusDtoMessage';

export interface AuthStatusDto {
  /** 인증여부 */
  authenticated?: boolean;
  /** 상태 메세지 */
  message?: AuthStatusDtoMessage;
}
