/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */

/**
 * 상태 메세지
 */
export type AuthStatusDtoMessage = typeof AuthStatusDtoMessage[keyof typeof AuthStatusDtoMessage];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AuthStatusDtoMessage = {
  LOGIN_USER: 'LOGIN_USER',
  INVALID_TOKEN: 'INVALID_TOKEN',
  NO_LOGIN_USER: 'NO_LOGIN_USER',
} as const;
