/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { BestRecordInfoCourseType } from './bestRecordInfoCourseType';

export interface BestRecordInfo {
  /** 대회 id */
  raceId?: number;
  /** 최고기록 */
  bestRecord?: string;
  /** 코스 정보 */
  courseType?: BestRecordInfoCourseType;
}
