/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */

export interface CheerZoneMemberDto {
  /** 그룹 멤버 ID */
  groupMemberId?: number;
  /** 멤버 ID */
  memberId?: number;
  /** 멤버 이름 */
  memberName?: string;
  /** 그룹명 */
  groupName?: string;
}
