/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { CheerZoneMemberDto } from './cheerZoneMemberDto';

export interface CheerZoneDetailResponseDto {
  /** 응원존 ID */
  zoneId?: number;
  /** 응원존명 */
  zoneName?: string;
  /** 응원존 라벨 */
  zoneLabel?: string;
  /** 거리 (km) */
  point?: number;
  /** 위도 */
  latitude?: number;
  /** 경도 */
  longitude?: number;
  /** 응원자 목록 */
  members?: CheerZoneMemberDto[];
  /** 응원존 생성자 ID */
  createdBy?: number;
}
