/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */

/**
 * 대회 기록조회 타입(SMARTCHIP, MYRESULT)
 */
export type CreateRaceRequestDtoRecordCd = typeof CreateRaceRequestDtoRecordCd[keyof typeof CreateRaceRequestDtoRecordCd];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateRaceRequestDtoRecordCd = {
  SMARTCHIP: 'SMARTCHIP',
  MYRESULT: 'MYRESULT',
  TIMESPCT: 'TIMESPCT',
  MANUAL: 'MANUAL',
} as const;
