/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { CreateRaceRequestDtoRecordCd } from './createRaceRequestDtoRecordCd';

export interface CreateRaceRequestDto {
  /** 마라톤 대회 id (1:서울마라톤, 2:JTBC, 3:춘천마라톤, 4:서울 하프 마라톤(4월), 5:서울레이스(9월)) */
  marathonId?: number;
  /** 시작일 */
  startDatetime?: string;
  /** 종료일 */
  endDatetime?: string;
  /** 대회 기록조회 타입(SMARTCHIP, MYRESULT) */
  recordCd?: CreateRaceRequestDtoRecordCd;
  /** 대회 번호(smartchip, myresult의 대회 번호 입력) */
  raceNo?: string;
}
