/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { CreateRaceMemberDtoCourse } from './createRaceMemberDtoCourse';

/**
 * 주자 정보
 */
export interface CreateRaceMemberDto {
  /** 배번 */
  bib?: string;
  /** 참여 코스 */
  course?: CreateRaceMemberDtoCourse;
  /** 목표 기록 (HH:mm:ss 형식) */
  targetRecord?: string;
}
