/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { CrewMemberApprovalRequestDtoStatusType } from './crewMemberApprovalRequestDtoStatusType';

/**
 * 크루 멤버 요청 승인/거절 요청 DTO (단일/일괄 처리 가능)
 */
export interface CrewMemberApprovalRequestDto {
  /** 크루 ID */
  crewId?: number;
  /** 멤버 ID 목록 (단일 또는 일괄 처리 가능) */
  memberIds?: number[];
  /** 상태값 (ACCEPT: 승인, DENY: 거절) */
  statusType?: CrewMemberApprovalRequestDtoStatusType;
}
