/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */

/**
 * 멤버 상태 (REQUEST, DENY, ACCEPT, WITHDRAWAL)
 */
export type CrewMemberResponseDtoStatus = typeof CrewMemberResponseDtoStatus[keyof typeof CrewMemberResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrewMemberResponseDtoStatus = {
  REQUEST: 'REQUEST',
  DENY: 'DENY',
  ACCEPT: 'ACCEPT',
  WITHDRAWAL: 'WITHDRAWAL',
} as const;
