/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { CrewMemberResponseDtoCrewRole } from './crewMemberResponseDtoCrewRole';
import type { CrewMemberResponseDtoStatus } from './crewMemberResponseDtoStatus';

export interface CrewMemberResponseDto {
  /** 멤버 ID */
  memberId?: number;
  /** 멤버 이름 */
  memberName?: string;
  /** 크루 역할 (CREW, MANAGER, ADMIN) */
  crewRole?: CrewMemberResponseDtoCrewRole;
  /** 멤버 상태 (REQUEST, DENY, ACCEPT, WITHDRAWAL) */
  status?: CrewMemberResponseDtoStatus;
  /** 승인한 운영진 ID (crew_member_id) */
  approverId?: number;
  /** 승인한 운영진 이름 */
  approverName?: string;
  /** 가입일 (YYYY-MM-DD 형식, ACCEPT 상태 변경일) */
  joinedDate?: string;
  /** 요청일 (YYYY-MM-DD 형식, CREW_MEMBER 생성일) */
  requestDate?: string;
}
