/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */

/**
 * 상태값 (ACCEPT: 승인, DENY: 거절)
 */
export type CrewMemberApprovalRequestDtoStatusType = typeof CrewMemberApprovalRequestDtoStatusType[keyof typeof CrewMemberApprovalRequestDtoStatusType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CrewMemberApprovalRequestDtoStatusType = {
  REQUEST: 'REQUEST',
  DENY: 'DENY',
  ACCEPT: 'ACCEPT',
  WITHDRAWAL: 'WITHDRAWAL',
} as const;
