/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */

/**
 * 러닝 상태
 */
export type DetailRaceHistoryResponseDtoStatus = typeof DetailRaceHistoryResponseDtoStatus[keyof typeof DetailRaceHistoryResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DetailRaceHistoryResponseDtoStatus = {
  READY: 'READY',
  RUNNING: 'RUNNING',
  FINISH: 'FINISH',
  DNF: 'DNF',
  DNS: 'DNS',
} as const;
