/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { DetailRaceHistoryResponseDtoCourse } from './detailRaceHistoryResponseDtoCourse';
import type { DetailRaceHistoryResponseDtoStatus } from './detailRaceHistoryResponseDtoStatus';
import type { RaceTrackResponseDto } from './raceTrackResponseDto';

export interface DetailRaceHistoryResponseDto {
  /** raceId */
  raceId?: number;
  /** 대회명 */
  raceTitle?: string;
  /** 대회 날짜 */
  raceDate?: string;
  /** 주자명 */
  memberName?: string;
  /** 배번 */
  bib?: string;
  /** 참여 코스 */
  course?: DetailRaceHistoryResponseDtoCourse;
  /** 러닝 상태 */
  status?: DetailRaceHistoryResponseDtoStatus;
  /** 코스 거리 */
  courseDistance?: number;
  /** 평균 페이스 */
  avgPace?: string;
  /** 대회 기록 */
  record?: string;
  /** 대회 split 기록 */
  tracks?: RaceTrackResponseDto[];
  /** 대회 기록증 사진 */
  raceRecordImg?: string;
}
