/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */

export type GetCrewMemberRequestsParams = {
/**
 * 멤버 이름 (완전일치 검색, 선택사항)
 */
memberName?: string;
/**
 * 페이지 정보
 */
page?: number;
/**
 * 페이지 크기
 */
size?: number;
/**
 * 정렬 필드
 */
sort?: string;
};
