/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */

export interface GlobalErrorResponse {
  /** Http Status */
  status?: number;
  /** Http Status error code */
  error?: string;
  /** custom error code */
  code?: string;
  /** error message */
  message?: string;
  /** timeStamp */
  timestamp?: string;
}
