/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { GroupMemberDto } from './groupMemberDto';

export interface GroupMemberSearchResponseDto {
  /** 검색된 그룹 멤버 목록 */
  members?: GroupMemberDto[];
}
