/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { MyCrewInfoResponseDto } from './myCrewInfoResponseDto';

export interface MemberResponseDto {
  /** memberId */
  memberId?: number;
  /** 이름 */
  memberName?: string;
  /** 프로필 이미지 */
  memberProfileImage?: string;
  /** 크루 소속 여부 */
  hasCrew?: boolean;
  /** 온보딩 완료 여부 */
  hasCompletedOnboarding?: boolean;
  /** 소속 크루 정보 */
  crewInfos?: MyCrewInfoResponseDto[];
}
