/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */

/**
 * 크루 회원 타입
 */
export type MyCrewInfoResponseDtoCrewRoleType = typeof MyCrewInfoResponseDtoCrewRoleType[keyof typeof MyCrewInfoResponseDtoCrewRoleType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MyCrewInfoResponseDtoCrewRoleType = {
  CREW: 'CREW',
  MANAGER: 'MANAGER',
  ADMIN: 'ADMIN',
} as const;
