/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { MyCrewInfoResponseDtoCrewRoleType } from './myCrewInfoResponseDtoCrewRoleType';

export interface MyCrewInfoResponseDto {
  /** crew id */
  crewId?: number;
  /** crew 명 */
  crewName?: string;
  /** crew 로고 이미지 url */
  crewImgUrl?: string;
  /** crew 색상(공사중) */
  crewColor?: string;
  /** 크루장 id */
  crewLeaderId?: number;
  /** 크루 회원 타입 */
  crewRoleType?: MyCrewInfoResponseDtoCrewRoleType;
}
