/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { CrewMemberResponseDto } from './crewMemberResponseDto';
import type { SortObject } from './sortObject';
import type { PageableObject } from './pageableObject';

export interface PageCrewMemberResponseDto {
  totalElements?: number;
  totalPages?: number;
  size?: number;
  content?: CrewMemberResponseDto[];
  number?: number;
  sort?: SortObject;
  numberOfElements?: number;
  pageable?: PageableObject;
  first?: boolean;
  last?: boolean;
  empty?: boolean;
}
