/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { RaceInfoDetailDtoCoursesItem } from './raceInfoDetailDtoCoursesItem';

export interface RaceInfoDetailDto {
  /** raceId */
  raceId?: number;
  /** 대회명 */
  raceTitle?: string;
  /** 대회 날짜 */
  raceDate?: string;
  /** 대회 시간 */
  raceTime?: string;
  /** 대회 장소 */
  place?: string;
  /** 대회 썸네일 사진 */
  raceImgUrl?: string;
  /** 대회 코스 목록 */
  courses?: RaceInfoDetailDtoCoursesItem[];
}
