/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { RaceHistoryResponseDtoCourse } from './raceHistoryResponseDtoCourse';

export interface RaceHistoryResponseDto {
  /** raceId */
  raceId?: number;
  /** raceTitle */
  raceTitle?: string;
  /** 대회 날짜 */
  raceDate?: string;
  /** 대회 시간 */
  raceTime?: string;
  /** 참여코스 */
  course?: RaceHistoryResponseDtoCourse;
  /** 기록 */
  record?: string;
  /** 대회 썸네일 사진 */
  raceRecordImg?: string;
}
