/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { RaceInfoResponseDtoRaceCoursesItem } from './raceInfoResponseDtoRaceCoursesItem';
import type { RaceInfoResponseDtoRecordType } from './raceInfoResponseDtoRecordType';

export interface RaceInfoResponseDto {
  /** raceId */
  raceId?: number;
  /** raceTitle */
  raceTitle?: string;
  /** 대회 날짜 */
  raceDate?: string;
  /** 대회 시간 */
  raceTime?: string;
  /** 대회 장소 */
  racePlace?: string;
  /** 대회 썸네일 사진 */
  raceImgUrl?: string;
  /** 코스정보 */
  raceCourses?: RaceInfoResponseDtoRaceCoursesItem[];
  /** 링크 */
  pageUrl?: string;
  /** 기록 타입 */
  recordType?: RaceInfoResponseDtoRecordType;
}
