/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { RaceInfoResponseDto } from './raceInfoResponseDto';
import type { RaceMemberResponseDto } from './raceMemberResponseDto';
import type { RaceGroupResponseDto } from './raceGroupResponseDto';

export interface RaceDetailDto {
  /** 대회 정보 */
  raceInfo?: RaceInfoResponseDto;
  /** 사용자 배번 등록 정보 */
  raceMemberInfo?: RaceMemberResponseDto;
  /** 참여 가능한 그룹 정보 */
  groupInfo?: RaceGroupResponseDto[];
}
