/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */

export type RaceInfoDetailDtoCoursesItem = typeof RaceInfoDetailDtoCoursesItem[keyof typeof RaceInfoDetailDtoCoursesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaceInfoDetailDtoCoursesItem = {
  FIVE: 'FIVE',
  TEN: 'TEN',
  ELEVEN: 'ELEVEN',
  HALF: 'HALF',
  THIRTY_TWO_K: 'THIRTY_TWO_K',
  FULL: 'FULL',
} as const;
