/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */

export interface RaceGroupResponseDto {
  /** crew 단위 그룹 여부(true/false) */
  crewGroup?: boolean;
  /** groupTitle */
  groupTitle?: string;
  /** 대회 기록 화면 key */
  broadCastKey?: string;
  /** 그룹 개설자 명 */
  groupAdminName?: string;
}
