/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { RaceMemberResponseDto } from './raceMemberResponseDto';

export interface RaceReportResponseDto {
  /** 스팟명 */
  courseTitle?: string;
  /** 통과현황 */
  passStatus?: string;
  /** 유저별 push알림 여부 */
  hasNotification?: boolean;
  /** 첫 번째 네트 타임 여부 (START 다음 스팟) */
  isFirstNetTime?: boolean;
  /** 거리 (km) */
  point?: number;
  /** 위도 */
  latitude?: number;
  /** 경도 */
  longitude?: number;
  /** 구간 ID */
  zoneId?: string;
  /** 스팟별 주자 정보 */
  raceMembers?: RaceMemberResponseDto[];
  firstNetTime?: boolean;
  /** 응원존 여부 */
  isCheerZone?: boolean;
}
