/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { RaceMemberResponseDtoStatus } from './raceMemberResponseDtoStatus';
import type { RaceMemberResponseDtoCourse } from './raceMemberResponseDtoCourse';

export interface RaceMemberResponseDto {
  /** 대회 id */
  raceId?: number;
  /** 대회 멤버 id */
  raceMemberId?: number;
  /** 회원 id */
  memberId?: number;
  /** 이름 */
  memberName?: string;
  /** 배번 */
  bib?: string;
  /** 상태(READY, RUNNING, FINISH, DNS, DNF) */
  status?: RaceMemberResponseDtoStatus;
  /** 참여코스 */
  course?: RaceMemberResponseDtoCourse;
  /** 착장 썸네일 사진 */
  thumbnailImgUrl?: string;
  /** 착장사진 */
  imgUrl?: string;
  /** 평균 페이스 */
  avgPace?: string;
  /** 예상 위치) */
  expectedDistance?: number;
  /** 기록 */
  record?: string;
  /** 진입 여부 */
  passingAlert?: boolean;
  /** 등록시간 */
  createdAt?: string;
  /** 목표 기록 (HH:mm:ss) */
  targetRecord?: string;
}
