/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { RaceReportResponseDto } from './raceReportResponseDto';

export interface RaceMemberReportWithTargetDto {
  /** 주자 기록 레포트 */
  raceReports?: RaceReportResponseDto[];
  /** 목표 기록(HH:mm:ss) */
  targetRecord?: string;
}
