/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */

/**
 * 기록 타입
 */
export type RaceInfoResponseDtoRecordType = typeof RaceInfoResponseDtoRecordType[keyof typeof RaceInfoResponseDtoRecordType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RaceInfoResponseDtoRecordType = {
  SMARTCHIP: 'SMARTCHIP',
  MYRESULT: 'MYRESULT',
  TIMESPCT: 'TIMESPCT',
  MANUAL: 'MANUAL',
} as const;
