/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { RaceGroupInfoBroadcastDto } from './raceGroupInfoBroadcastDto';

export interface RaceOverallBroadCastResponseDto {
  /** 그룹 정보 */
  raceGroupInfo?: RaceGroupInfoBroadcastDto;
  /** map polyline GPS, 기본 marker 정보 파일 url */
  mapUrl?: string;
}
