/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */
import type { RecordInfoResponseDtoCourse } from './recordInfoResponseDtoCourse';

export interface RecordInfoResponseDto {
  /** raceId */
  raceId?: number;
  /** raceTitle */
  raceTitle?: string;
  /** 대회 날짜 */
  raceDate?: string;
  /** 대회 장소 */
  racePlace?: string;
  /** 참여코스 */
  course?: RecordInfoResponseDtoCourse;
  /** 기록 */
  record?: string;
  /** 대회 썸네일 사진 */
  raceImgUrl?: string;
  /** 기록증 썸네일 사진 */
  recordImg?: string;
}
