/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */

/**
 * 사용자 이름 변경 요청 DTO
 */
export interface UpdateMemberNameRequestDto {
  /**
   * 새로운 사용자 이름
   * @minLength 1
   * @maxLength 20
   */
  memberName?: string;
}
