/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * YRC Race API
 * 여의도 러닝 크루 마라톤 기록 API
 * OpenAPI spec version: v1.0
 */

export interface UpdateRaceCheerZoneDto {
  /**
   * 라벨
   * @minLength 1
   */
  pointLabel?: string;
  /** 거리 */
  point: number;
  /**
   * 위도 (선택사항, 없으면 marathon_gps_infos에서 자동 조회)
   * @minimum -90
   * @maximum 90
   */
  latitude?: number;
  /**
   * 경도 (선택사항, 없으면 marathon_gps_infos에서 자동 조회)
   * @minimum -180
   * @maximum 180
   */
  longitude?: number;
  /** 응원존 멤버 ID 목록 */
  groupMemberIds?: number[];
}
